### PR TITLE
Application Gateway creation

### PR DESCRIPTION
**Pull request by briandenicola**
This pull request includes the bicep code to create an Application Gateway for the construction set.  Please review readme.md for details on to test out the code.

### CODE REVIEW

**Comment by seenu433** [comment]
@briandenicola - 

Reviewed it but could not test due to cert dependencies

Below are my thoughts to remove the dependencies
- Can we target http if no certificate is provided
- Assign a DNS label on pip if no value provided for the fqdn

    dnsSettings: {
      domainNameLabel: 'string'
      fqdn: 'string'
      reverseFqdn: 'string'
    }

**Comment by briandenicola** [comment]
> @briandenicola -
> 
> Reviewed it but could not test due to cert dependencies
> 
> Below are my thoughts to remove the dependencies
> 
> * Can we target http if no certificate is provided
> * Assign a DNS label on pip if no value provided for the fqdn
>   dnsSettings: {
>   domainNameLabel: 'string'
>   fqdn: 'string'
>   reverseFqdn: 'string'
>   }

My understanding of the design was that HTTPs will be required. And since HTTPs is required then we can not use the DNS label on the PIP because it will use {location}.cloudapp.azure.com.

If possible I would like to merge this into the main branch and then take your suggestions as feature request for the backlog.

**Comment by briandenicola** [comment]
> @briandenicola, I compared this to my own AG/APIM setup, and your PR is very comprehensive from what I can tell. What would be the best way to test it, please?

Please see the [readme.md](https://github.com/cykreng/Enterprise-Scale-APIM/tree/brdenico/dev/deployment/bicep/gateway) with steps to test/validate the cod. If need assistance with the steps, please let me know.

**Comment by seenu433** [comment]
@briandenicola - I tried testing it but its failing with a password protected cert file. I tried updating it to use a password but it seems that the password works with data field and not the keyVaultSecretId.

**Comment by seenu433** [comment]
I was able to test this end to end with a password-less cert. Below are some observations

- Unused Resource Group  Line 74-79 in main.bicep
- Unused PIP in the networking resource group. Not sure if it should be the one to be used for app gateway
- There is no PIP assigned to the jumpbox
- NSG rules to be verified for the best practices. For ex. rdp etc.
- Naming convention is not the same across all resources
- Unused variables

- Need to make it work with a password protected cert file

**Comment by briandenicola** [comment]
> I was able to test this end to end with a password-less cert. Below are some observations
> 
> * Unused Resource Group  Line 74-79 in main.bicep
> * Unused PIP in the networking resource group. Not sure if it should be the one to be used for app gateway
> * There is no PIP assigned to the jumpbox
-- These observations are outside the code for this pull request. I do not create or touch any object in the networking resource group or any additional PIPs.  

> * Naming convention is not the same across all resources
-- Which resources are not following convention?  All resources created by this pull request follow                 '{resource}-${resourceSuffix}'.  If there are resources outside of bicep\gateway then that's already in the main branch and outside the scope of the pull request.
 
> * Unused variables
Do you list of that of these variables so I can review?

> * Need to make it work with a password protected cert file
-- Bicep currently does not support this unless I am mistaken.  Bicep only supports secrets and keys, not ceritificates. And certificate objects are the only ones that can support a password on the pfx file. If you have sample code on how to use bicep with certificates, please share and I'll update the code. 

> * NSG rules to be verified for the best practices. For ex. rdp etc.
I followed NSG rules for AppGateway based on the following - https://docs.microsoft.com/en-us/azure/application-gateway/configuration-infrastructure#network-security-groups

**Pull request merged**
