### PR TITLE
Updated shared rg with agent fixes

### PR DESCRIPTION
**Pull request by ahmedsza**
Updated this to sync with app service
Allows you to create GH runner or AZ pipeline or none
Fixed versioning
Updated names /parameters

### CODE REVIEW

**Comment by seenu433** [comment]
@ahmedsza - Below are my observations

paramters file not updated with the below params 
 - rename vmdevopsUsername, vmdevopsPassword, devopsurl to accountName
 - orgtype to be added

Orgtype none not handled. The VM is created.

DevOps agent is not showing up in ADO agent pool

I haven't tested it for Github

**Comment by ahmedsza** [comment]
Thanks @seenu433 . Seems like I did port (aka copy and paste 😃)  all the changes from the appservice implementation.  Will review on Monday

**Comment by cykreng** [comment]
@ahmedsza - can we change orgtype to CICDAgentType to be consistent with the ASE repo? Thanks!

**Comment by ahmedsza** [comment]
@cykreng . I see there has been a decent number of changes in the ASE repo. I will need to review all of this, and then update this repo. I am half tempted to close this PR for now - and then open a new one after i looked at this 
Maybe we should have gone with one repo :-). Keeping the 2 repos in sync is proving challenging.

**Comment by ahmedsza** [comment]
@seenu433 , @cykreng , @whsalazar  - made lots of changes to incorporate the changes in ASE, including request on changing the  orgtype. Tested on my side -  but if you can review, and test please

**Comment by whsalazar** [comment]
Tested code, fixed conflict with main for main.bicep by adding   workloadName and  environment as parameters to backend.bicep module

**Pull request merged**
